export const publicGalleryImages = [
  {
    id: 1,
    title: 'Coding Class',
    description: 'Students engaged in hands-on programming sessions.',
    category: 'Classrooms',
    imgSrc: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
    alt: 'Coding class at ANSDB skill development institute in Bolpur',
    big: true,
  },
  {
    id: 2,
    title: 'Hardware Repair',
    description: 'Detailed practical training on computer hardware.',
    category: 'Workshops',
    imgSrc: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=400&q=80',
    alt: 'Hardware repair vocational training workshop at ANSDB Bolpur',
  },
  {
    id: 3,
    title: 'Circuit Board',
    description: 'Advanced electronics design and testing.',
    category: 'Labs',
    imgSrc: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=400&q=80',
    alt: 'Electronics and circuit board practical training at ANSDB in Bolpur',
  },
  {
    id: 4,
    title: 'Computer Lab',
    description: 'Fully equipped modern computing facilities.',
    category: 'Labs',
    imgSrc: '/images/gallery/IMG_4784.jpg',
    alt: 'Computer lab at ANSDB computer centre in Bolpur',
  },
  {
    id: 5,
    title: 'Technical Work',
    description: 'Practical field training and equipment maintenance.',
    category: 'Workshops',
    imgSrc: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=400&q=80',
    alt: 'Technical field training and equipment practice at ANSDB Bolpur',
  },
  {
    id: 6,
    title: '',
    description: '',
    imgSrc: '/images/gallery/IMG_20260401_141937.jpg',
    alt: 'ANSDB gallery image',
  },
  {
    id: 7,
    title: '',
    description: '',
    imgSrc: '/images/gallery/IMG_4779.jpg',
    alt: 'ANSDB gallery image',
  },
  {
    id: 8,
    title: '',
    description: '',
    imgSrc: '/images/gallery/IMG_4783.jpg',
    alt: 'ANSDB gallery image',
  },
  {
    id: 9,
    title: '',
    description: '',
    imgSrc: '/images/gallery/IMG_4784.jpg',
    alt: 'ANSDB gallery image',
  },
];